// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDItvj8l0F6NTrEmm9_NfIVz4mBzQYvI5Q',
    appId: '1:512403023667:web:06ff240e7b4c6d63be4046',
    messagingSenderId: '512403023667',
    projectId: 'light-vinted',
    authDomain: 'light-vinted.firebaseapp.com',
    storageBucket: 'light-vinted.appspot.com',
    measurementId: 'G-TB2R82MDDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNLn0Cdx7_y7jZWLwDuP1Z3fvue2qR7Ds',
    appId: '1:512403023667:android:d534fb4d56fd2aefbe4046',
    messagingSenderId: '512403023667',
    projectId: 'light-vinted',
    storageBucket: 'light-vinted.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDLDgdTwWVoVoCCVUKzNZo9wo95-1YdWQ',
    appId: '1:512403023667:ios:890bdc63fb080b1abe4046',
    messagingSenderId: '512403023667',
    projectId: 'light-vinted',
    storageBucket: 'light-vinted.appspot.com',
    iosBundleId: 'com.example.lightVinted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDLDgdTwWVoVoCCVUKzNZo9wo95-1YdWQ',
    appId: '1:512403023667:ios:890bdc63fb080b1abe4046',
    messagingSenderId: '512403023667',
    projectId: 'light-vinted',
    storageBucket: 'light-vinted.appspot.com',
    iosBundleId: 'com.example.lightVinted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDItvj8l0F6NTrEmm9_NfIVz4mBzQYvI5Q',
    appId: '1:512403023667:web:977cc5c822190d4cbe4046',
    messagingSenderId: '512403023667',
    projectId: 'light-vinted',
    authDomain: 'light-vinted.firebaseapp.com',
    storageBucket: 'light-vinted.appspot.com',
    measurementId: 'G-T3WLKEYBEK',
  );
}
